version: '3.4'

networks:
  backendlive:

services:  
    WebApiGateway:
        container_name: api-webapigateway
        image: tuannl/gatewayapi
        ports:
          - 8082:80
        networks:
          - backendlive
    accountsapi:
        container_name: api-accountsapi
        image: tuannl/accountapi    
        networks:
          - backendlive
    portfoliowebapi:
        container_name: api-portfolio
        image: tuannl/portfolioapi
        networks:
          - backendlive

